version: '2'
services:
    api-gateway:
        image: caenietoba/api-gateway:1.0
        labels:
            - api=api
        environment:
            PORT: '5000'
            SHOW_URLS: 'true'
            TRADINGS_URL: 'tradings-ms'
            TRADINGS_PORT: '4005'
            TRADINGS_ENTRY: 'trading'
            PRODUCTS_URL: 'products-ms'
            PRODUCTS_PORT: '4006'
            PRODUCTS_ENTRY: 'products'
            STORES_URL: 'stores-ms'
            STORES_PORT: '3001'
            STORES_ENTRY: 'stores-ms/resources/stores'
            USERS_URL: 'users-ms'
            USERS_PORT: '3000'
            USERS_ENTRY: 'users-ms/resources/users'
            LOGIN_URL: 'users-ms'
            LOGIN_PORT: '3000'
            LOGIN_ENTRY: 'users-ms/resources/auth'
        ports:
            - '5000:5000'

api-gateway:
    scale: 2